### PR TITLE
New sapic constructs

### PR DESCRIPTION
**Pull request by rkunnema**
Hi!

New vim stuff.

1. Added new constructs in SAPIC to be uptodate with `develop`.

2. Include these constructs in the syntax file for .spthy

3. created a simple syntax for .sapic that just links to the one for .spthy

4. I propose to have a branch `develop` in editors as well, for when syntax is different in those branches. The PR includes a README.md with instructions how to use this.

I was not able to create a `develop` branch myself, so if you are ok with (4), please merge with that branch instead of `master`.

### CODE REVIEW

**Comment by cascremers** [comment]
Hi Robert,

Thanks!

>     I propose to have a branch |develop| in editors as well, for when
>     syntax is different in those branches. The PR includes a README.md
>     with instructions how to use this.

There is a wider issue here though: we are planning to merge the manual
repo back into the source code repo, because that would make it easier
to keep documentation synchronised with the code. A similar argument
could be made for syntax files (as you noticed :-) ).

Maybe this is something the maintainers should discuss for a bit.

Best,

Cas

**Comment by rkunnema** [comment]
I thought about this, too, but there is a major downside with this: vim's plugin manager (and anything using git, really) would clone the whole repository for just this small 40kb of text files. On the other hand, syntax changes are not that frequent.

**Comment by rkunnema** [comment]
Link to current discussion: https://github.com/tamarin-prover/tamarin-prover/pull/349

**Comment by rkunnema** [comment]
superseded by https://github.com/tamarin-prover/editors/pull/4. Closing.

**Pull request closed without merging**
